# Generated by Django 6.0 on 2026-01-04 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='income',
        ),
        migrations.AddField(
            model_name='customuser',
            name='looking_for_gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('couple', 'Пара М+Ж')], default='female', max_length=10, verbose_name='Кого ищете'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вопрос 1 (для гостей)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вопрос 2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='question3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Вопрос 3'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('gold', 'Gold ⭐️'), ('vip', 'VIP 👑')], default='free', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('jerusalem', 'Иерусалим'), ('tlv', 'Тель-Авив'), ('haifa', 'Хайфа'), ('rishon', 'Ришон-ле-Цион'), ('ashdod', 'Ашдод'), ('beersheva', 'Беэр-Шева'), ('netanya', 'Нетания'), ('akko', 'Акко'), ('arad', 'Арад'), ('ariel', 'Ариэль'), ('afula', 'Афула'), ('ashkelon', 'Ашкелон'), ('batyam', 'Бат-Ям'), ('beitshean', 'Бейт-Шеан'), ('beitshemesh', 'Бейт-Шемеш'), ('bneibrak', 'Бней-Брак'), ('herzliya', 'Герцлия'), ('givataim', 'Гиватаим'), ('dimona', 'Димона'), ('eilat', 'Эйлат'), ('karmiel', 'Кармиэль'), ('kfar_sava', 'Кфар-Сава'), ('lod', 'Лод'), ('nahariya', 'Нагария'), ('nazareth', 'Назарет'), ('petah_tikva', 'Петах-Тиква'), ('raanana', 'Раанана'), ('ramat_gan', 'Рамат-Ган'), ('rehovot', 'Реховот'), ('tiberias', 'Тверия'), ('hadera', 'Хадера'), ('holon', 'Холон'), ('other', 'Другой город')], default='tlv', max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('couple', 'Пара М+Ж')], max_length=10, verbose_name='Кто вы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='goal',
            field=models.CharField(choices=[('friendship', 'Дружба/Общение'), ('serious', 'Серьезные отношения'), ('date_evening', 'Свидание на вечер'), ('travel', 'Попутчики')], default='serious', max_length=20, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.TextField(blank=True, verbose_name='Интересы (теги)'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('like', '❤️ Лайк'), ('star', '⭐️ Избранное'), ('check', '✅ Готов встретиться')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sender', 'receiver', 'type')},
            },
        ),
    ]
