# Generated by Django 6.0 on 2026-01-04 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('general', '📢 Общий чат'), ('tlv', '🏖️ Тель-Авив тусовка'), ('relationships', '❤️ Про отношения'), ('hobby', '🎨 Хобби и интересы'), ('travel', '🚗 Попутчики по Израилю')], max_length=20, verbose_name='Комната')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
