# Generated by Django 6.0 on 2026-01-04 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('jerusalem', 'Иерусалим'), ('tlv', 'Тель-Авив'), ('haifa', 'Хайфа'), ('rishon', 'Ришон-ле-Цион'), ('ashdod', 'Ашдод'), ('beersheva', 'Беэр-Шева'), ('netanya', 'Нетания'), ('divider', '————'), ('akko', 'Акко'), ('arad', 'Арад'), ('ariel', 'Ариэль'), ('afula', 'Афула'), ('ashkelon', 'Ашкелон'), ('baka', 'Бака-эль-Гарбия'), ('batyam', 'Бат-Ям'), ('beitar', 'Бейтар-Илит'), ('beitshean', 'Бейт-Шеан'), ('beitshemesh', 'Бейт-Шемеш'), ('beeryakov', 'Беэр-Яаков'), ('bneibrak', 'Бней-Брак'), ('gefer', 'Гефер-Явне'), ('herzliya', 'Герцлия'), ('givataim', 'Гиватаим'), ('givatshmuel', 'Гиват-Шмуэль'), ('dimona', 'Димона'), ('elad', 'Елaд'), ('yehud', 'Йехуд-Моноссон'), ('yokneam', 'Йокнеам-Илит'), ('karmiel', 'Кармиэль'), ('cesarea', 'Кесария'), ('kalansua', 'Калансуа'), ('kafrkase', 'Кафр-Касем'), ('kfar_sava', 'Кфар-Сава'), ('kiryatata', 'Кирьят-Ата'), ('kiryatbialik', 'Кирьят-Бялик'), ('kiryatgat', 'Кирьят-Гат'), ('kiryatmalahi', 'Кирьят-Малахи'), ('kiryatmotzkin', 'Кирьят-Моцкин'), ('kiryatono', 'Кирьят-Оно'), ('kiryatshmona', 'Кирьят-Шмона'), ('kiryatyam', 'Кирьят-Ям'), ('lod', 'Лод'), ('maale', 'Маале-Адумим'), ('maalot', 'Маалот-Таршиха'), ('migdal', 'Мигдаль-ха-Эмек'), ('modiinilit', 'Модиин-Илит'), ('modiin', 'Модиин-Маккабим-Реут'), ('nazareth', 'Назарет'), ('nahariya', 'Нагария'), ('ofakim', 'Офаким'), ('petah_tikva', 'Петах-Тиква'), ('raanana', 'Раанана'), ('ramat_gan', 'Рамат-Ган'), ('ramatsharon', 'Рамат-ха-Шарон'), ('ramla', 'Рамла'), ('rahat', 'Рахат'), ('rehovot', 'Реховот'), ('rosh', 'Рош-ха-Аин'), ('sderot', 'Сдерот'), ('tiberias', 'Тверия'), ('tlv_jaffa', 'Тель-Авив-Яффо'), ('tira', 'Тира'), ('tirat', 'Тират-Кармиш'), ('umm', 'Умм-эль-Фахм'), ('hader', 'Хадера'), ('holon', 'Холон'), ('eilat', 'Эйлат'), ('other', 'Другой город')], default='tlv', max_length=50, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(choices=[(1, 'Вопрос 1'), (2, 'Вопрос 2'), (3, 'Вопрос 3')], verbose_name='Номер вопроса')),
                ('question_text', models.CharField(max_length=100, verbose_name='Текст вопроса')),
                ('answer_text', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата ответа')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_answers', to=settings.AUTH_USER_MODEL, verbose_name='Кому ответили')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to=settings.AUTH_USER_MODEL, verbose_name='Кто ответил')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
